version: '3.8'

services:
  calculator-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge
